name: Build and Deploy on DEV environment

on:
    push:
        branches:
            - dev
permissions:
    id-token: write
    contents: read

concurrency:
  group: dev_environment
  cancel-in-progress: true

jobs:
    unit-test:
        runs-on: ubuntu-latest
        name: Pass unit tests
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{secrets.CLIENTELING_COMMONS_SSH_KEY}}
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test -- run
    build-and-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        needs: unit-test
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.8.0
              with:
                ssh-private-key: ${{secrets.CLIENTELING_COMMONS_SSH_KEY}}
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Docker Registry Login
              uses: docker/login-action@v2
              with:
                  username: ${{secrets.DEV_AZURE_REGISTRY_USERNAME}}
                  password: ${{secrets.DEV_AZURE_REGISTRY_PASSWORD}}
                  registry: ${{secrets.DEV_AZURE_REGISTRY_URL}}
            - name: Docker Build
              run: docker build -t ${{secrets.DEV_AZURE_REGISTRY_URL}}/clienteling-TODO_CHANGEME:${{ github.sha }} --build-arg APPLICATION_INSIGHT_KEY="${{secrets.DEV_APPLICATION_INSIGHT_KEY}}" .
            - name: Docker Push
              run: docker push ${{secrets.DEV_AZURE_REGISTRY_URL}}/clienteling-TODO_CHANGEME:${{ github.sha }}
            - name: Azure Login
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.DEV_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Update container app
              uses: azure/container-apps-deploy-action@v1
              with:
                  containerAppName: clienteling-TODO_CHANGEME
                  resourceGroup: clienteling-dev
                  imageToDeploy: ${{secrets.DEV_AZURE_REGISTRY_URL}}/clienteling-TODO_CHANGEME:${{ github.sha }}
