name: Check deployment

on:
    workflow_run:
        workflows: ['Build and Deploy']
        types:
            - completed
permissions:
    id-token: write
    contents: read

jobs:
    check-deployment:
        runs-on: ubuntu-latest
        name: Check that latest revision has been well deployed
        environment: ${{ github.ref_name }}
        steps:
            - name: Azure Login
              uses: Azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Check if revisions are healthy
              run: |
                  unhealthy_container=$(az containerapp revision list -n [SERVICE_NAME_IN_AZURE] -g clienteling-${{ github.ref_name }} | jq '.[] | select(.properties.healthState == "Unhealthy")')
                  if [[ -n $unhealthy_container ]]; then
                    echo "::error::Some resources have unhealthy state"
                    exit 1
                  fi
            - name: Send success notif to Teams
              if: ${{ success() }}
              run: |
                  curl -X POST ${{secrets.TEAMS_WEBHOOK_URL}} -H "Content-Type: application/json" -d '{"text": "The service [SERVICE_NAME_IN_AZURE] has been well deployed in ${{ github.ref_name }} environment", "wrap": true}'
            - name: Send failure notif to Teams
              if: ${{ failure() }}
              run: |
                  curl -X POST ${{secrets.TEAMS_WEBHOOK_URL}} -H "Content-Type: application/json" -d '{"text": "The service [SERVICE_NAME_IN_AZURE] is not healthy in ${{ github.ref_name }} environment.", "wrap": true}'
