name: Clienteling Pull requests validation

on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        branches:
            - 'CHANGE-IT-TO-dev'

jobs:
    unit-test:
        runs-on: ubuntu-latest
        name: Pass unit tests
        steps:
            - uses: actions/checkout@v4
            - uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{secrets.CLIENTELING_COMMONS_SSH_KEY}}
            - uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci
            - name: Type check
              run: npm run type-check
            - name: run unit tests
              run: npm test -- run --coverage
            - name: run integrations tests
              run: npm run test:integration
            - name: Code Coverage Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                  filename: coverage/cobertura-coverage.xml
                  badge: true
                  format: markdown
                  output: both
            - name: Adding summary
              run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
